export const languages = {
    en: {
        home: 'Home',
        about: 'About',
        aboutpage: 'About this site',
        contact: 'Contact',
        brightness: 'Brightness',
        tags: 'Tags',
        archive: 'Archive',
        langs: 'Languages',
        langposts: 'Posts in English',
        published: 'Published',
        tagged: 'Tagged:',
        typetag: 'Tagged',
        alltags: 'All Tags',
        locale: 'en-US',
        said: 'said:',
        commentsingular: 'comment',
        commentplural: 'comments',
        commentzero: 'No comments',
        error: 'Something went wrong.',
        backhome: 'Back to the home page',

    },
    hu: {
        home: 'Főoldal',
        about: 'Erről',
        aboutpage: 'Erről az oldalról',
        contact: 'Kapcsolat',
        brightness: 'Napsütés',
        tags: 'Témák',
        archive: 'Archivum',
        langs: 'Nyelvek',
        langposts: 'Magyar nyelvű cikkek',
        published: '-en közzétett',
        tagged: 'Ezekkel a témákkal:',
        typetag: 'témával',
        alltags: 'Minden téma',
        locale: 'hu-HU',
        said: 'azt mondta, hogy:',
        commentsingular: 'komment',
        commentplural: 'komment',
        commentzero: 'Nincs komment',
        error: 'Valami elromlott.',
        backhome: 'Hátra a főoldalra',
    },
    de: {
        home: 'Startseite',
        about: 'Über',
        aboutpage: 'Über dieser Seite',
        contact: 'Kontakt',
        brightness: 'Helligkeit',
        tags: 'Tags',
        archive: 'Archiv',
        langs: 'Sprache',
        langposts: 'Beiträge auf Deutsch',
        published: 'Veröffentlicht am',
        tagged: 'Mit dieser Tags:',
        typetag: 'Mit Tag',
        alltags: 'Alle Tags',
        locale: 'de-DE',
        said: 'hat gesagt:',
        commentsingular: 'Kommentar',
        commentplural: 'Kommentare',
        commentzero: 'Keine Kommentare',
        error: 'Etwas ist schiefgelaufen.',
        backhome: 'Zurück zur Startseite',
    }
}