export const languages = {
    en: {
        home: 'Home',
        about: 'About',
        contact: 'Contact',
        brightness: 'Brightness',
        tags: 'Tags',
        archive: 'Archive',
        langs: 'Languages',
        langposts: 'Posts in English',
        published: 'Published',
        tagged: 'Tagged:',
        typetag: 'Tagged',
        alltags: 'All Tags',
        locale: 'en-US',
    },
    hu: {
        home: 'Főoldal',
        about: 'Erről',
        contact: 'Kapcsolat',
        brightness: 'Napsütés',
        tags: 'Témák',
        archive: 'Archivum',
        langs: 'Nyelvek',
        langposts: 'Magyar nyelvű cikkek',
        published: '-en közzétett',
        tagged: 'Ezekkel a témákkal:',
        typetag: 'témával',
        alltags: 'Minden téma',
        locale: 'hu-HU', 
    },
    de: {
        home: 'Startseite',
        about: 'Über',
        contact: 'Kontakt',
        brightness: 'Helligkeit',
        tags: 'Tags',
        archive: 'Archiv',
        langs: 'Sprache',
        langposts: 'Beiträge auf Deutsch',
        published: 'Veröffentlicht am',
        tagged: 'Mit dieser Tags:',
        typetag: 'Mit Tag',
        alltags: 'Alle Tags',
        locale: 'de-DE',
    }
}